# Generated by Django 2.0.4 on 2019-04-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190417_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
