# Generated by Django 2.0.4 on 2019-04-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='video_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
