# Generated by Django 2.0.4 on 2019-04-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blog_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
    ]
