# Generated by Django 2.0.4 on 2019-04-21 13:34

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_blogauthor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
