# Generated by Django 2.2 on 2019-04-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_auto_20190426_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blogs.BlogComment'),
        ),
    ]
