# Generated by Django 2.2 on 2019-04-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_auto_20190426_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='reply',
            new_name='parent',
        ),
    ]
